name: pet_drinking_monitor # หรือ pet_water_tracker_new ตามชื่อโปรเจกต์
description: แอปพลิเคชันติดตามการดื่มน้ำของสัตว์เลี้ยง.
version: 1.0.1+2 # อัปเดตเวอร์ชันตามความเหมาะสม

environment:
  sdk: ">=2.19.0 <4.0.0" # ตรวจสอบเวอร์ชัน SDK ของคุณ

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5 # <--- ตรวจสอบว่ามี provider
  shared_preferences: ^2.2.1
  mqtt_client: ^10.0.0
  fl_chart: ^0.63.0
  flutter_local_notifications: ^15.1.0+1 # หรือเวอร์ชันล่าสุด
  intl: ^0.18.1
  timezone: ^0.9.2
  uuid: ^4.3.3 # <--- เพิ่ม uuid package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Regular.ttf
        - asset: assets/fonts/Kanit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Kanit-Light.ttf
          weight: 300
        - asset: assets/fonts/Kanit-Italic.ttf
          style: italic